spring:
  profiles: dev
  application:
    name: activity-recognition
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/forest_fire_monitor_db
    username: ffm_admin
    password: ffm_admin
    initialization-mode: always
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.hibernate: INFO