spring:
  application:
    name: activity-recognition
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PSQL_HOST:localhost}:5432/forest_fire_monitor_db
    username: ffm_admin
    password: ffm_admin
    initialization-mode: always
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
    com.ffm.backend.service.NotificationSenderService: DEBUG
notifications:
  diagonal-meters: 5000
  interval-milliseconds: 300000
  hazard-threshold: 50


